---
language: ruby
sudo: required
services:
  - docker
script:
  - bundle exec rspec spec/acceptance
bundler_args: --without system_tests
matrix:
  include:
  - rvm: default
    env: LINT=puppetcode
    dist: trusty
    bundler_args:
    script: bundle exec rake lint
  - rvm: default
    env: LINT=metadata
    dist: trusty
    bundler_args:
    script: bundle exec rake metadata_lint
  - rvm: default
    env: JOB=validate
    dist: trusty
    bundler_args:
    script: bundle exec rake validate
  - rvm: default
    env: TIPUS="server" BEAKER_set="centos7-docker"
    dist: trusty
    bundler_args:
    script: sudo service docker restart ; sleep 10 && bundle exec rspec spec/acceptance/server_spec.rb
  - rvm: default
    env: TIPUS="server" BEAKER_set="ubuntu16-docker"
    dist: trusty
    bundler_args:
    script: sudo service docker restart ; sleep 10 && bundle exec rspec spec/acceptance/server_spec.rb
  - rvm: default
    env: TIPUS="client" BEAKER_set="centos6-docker"
    dist: trusty
    bundler_args:
    script: sudo service docker restart ; sleep 10 && bundle exec rspec spec/acceptance/client_spec.rb
  - rvm: default
    env: TIPUS="client" BEAKER_set="centos7-docker"
    dist: trusty
    bundler_args:
    script: sudo service docker restart ; sleep 10 && bundle exec rspec spec/acceptance/client_spec.rb
  - rvm: default
    env: TIPUS="client" BEAKER_set="ubuntu14-docker"
    dist: trusty
    bundler_args:
    script: sudo service docker restart ; sleep 10 && bundle exec rspec spec/acceptance/client_spec.rb
  - rvm: default
    env: TIPUS="client" BEAKER_set="ubuntu16-docker"
    dist: trusty
    bundler_args:
    script: sudo service docker restart ; sleep 10 && bundle exec rspec spec/acceptance/client_spec.rb
